### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 

### ISSUE THREAD

**Issue by zhuthesea** [brandonxiang/pb-to-typescript#17]
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/local/lib/node_modules/pbts/node_modules/@pbts/core/src/index.js' imported from /usr/local/lib/node_modules/pbts/src/index.js
    at new NodeError (node:internal/errors:387:5)
    at finalizeResolution (node:internal/modules/esm/resolve:330:11)
    at moduleResolve (node:internal/modules/esm/resolve:907:10)
    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

node:v16.18.0

**Comment by zhuthesea** [comment]
cp core/src. resolved.

**Comment by zhuthesea** [comment]
cp core/src/   . has been resolved

**Comment by zhuthesea** [comment]
file:///usr/local/lib/node_modules/pbts/node_modules/@pbts/core/src/index.js:80
      return result.join('');
                    ^

TypeError: result.join is not a function
    at parseProtoRoot (file:///usr/local/lib/node_modules/pbts/node_modules/@pbts/core/src/index.js:80:21)
    at convertAction (file:///usr/local/lib/node_modules/pbts/src/index.js:48:24)
    at o.parse (/usr/local/lib/node_modules/pbts/node_modules/sade/lib/index.js:1:3402)
    at file:///usr/local/lib/node_modules/pbts/bin.js:26:8

**Comment by verybigorange** [comment]
I had the same problem. 
node: v16.18.1
pbts: ^3.0.0

**Comment by brandonxiang** [comment]
release 3.0.1
